name: simple_dial_code
description: A lightweight, zero-dependency package to convert between country ISO codes and telephone dialing codes.
version: 1.0.0
homepage: https://github.com/KULLANICI_ADIN/simple_dial_code 

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0